/*
 * DESIGN PATTERN
 *
 * Factory Method
 *
 * Generated by Secure Web Architecture Toolkit.
 *
 * Review and adapt before production.
 */
interface Product
{
    public function execute(): void;
}

final class ConcreteProduct
    implements Product
{
    public function execute(): void
    {
    }
}

abstract class Creator
{
    abstract protected function
        createProduct(): Product;

    public function run(): void
    {
        $product =
            $this->createProduct();

        $product->execute();
    }
}

final class ConcreteCreator
    extends Creator
{
    protected function
        createProduct(): Product
    {
        return new ConcreteProduct();
    }
}